---
- name: Install dependencies
  xbps:
    pkg:
      - ruby
      - ruby-devel
      - nodejs
      - base-devel
      - git
      - rsync
    state: present

- name: Install firewall rules
  template:
    src: jekyll.rules
    dest: /etc/iptables.d/jekyll.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables

- name: Install Jekyll
  gem:
    name: "{{ item }}"
    state: present
    user_install: no
  with_items:
    - jekyll
    - jekyll-paginate
    - bundler

- name: Configure Webserver
  include_role:
    name: nginx
    tasks_from: base-site
  with_items: "{{ jekyll_sites }}"
  vars:
    - site: "{{ item }}"

- name: Install site build script
  template:
    src: jekyll_build.sh
    dest: /usr/local/sbin/jekyll-build
    owner: root
    group: root
    mode: 0755

- name: Add cron job for site
  template:
    src: jekyll_build.cron
    dest: /etc/cron.d/jekyll_build
    owner: root
    group: root
    mode: 0644
